services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src'

    Symfony\Component\Console\Application:
        public: true

    App\Command\GamePlayCommand:
        public: true
